export { TONE_IDS, TONE_ROWS } from '$lib/constants/state/toneRows'

export const PPQ = 96
export const DEFAULT_BPM = 93
export const MS_PER_MINUTE = 60000
export const MS_PER_BEAT = MS_PER_MINUTE / DEFAULT_BPM
export const MS_PER_BEAT_DIVISION = MS_PER_BEAT / 4
export const DEFAULT_MS_PER_BEAT = MS_PER_MINUTE / DEFAULT_BPM
export const DEFAULT_MS_PER_DIVISION = DEFAULT_MS_PER_BEAT / 4
export const DEFAULT_BPM_DIVISIONS = 4
export const MAX_BEATS_PER_PATTERN = 128
export const MAX_DIVISIONS_PER_PATTERN = MAX_BEATS_PER_PATTERN * DEFAULT_BPM_DIVISIONS

export const PATTERN_GRID = {
	DIVISIONS_PER_BEAT: 4,
	BEAT_WIDTH: 40,
	DIVISION_WIDTH: 10,
	ROW_HEIGHT: 32
}
